--    create table student (
--       id integer not null auto_increment,
--        classNo varchar(255) not null,
--        name varchar(255) not null,
--        score integer not null,
--        primary key (id)
--    ) engine=InnoDB;
